# Generated by Django 3.2.4 on 2023-07-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myAdminPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField()),
                ('slugTitle', models.SlugField(max_length=100)),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
